### ISSUE TITLE
pip install giving endless OpenBLAS warnings

### ISSUE THREAD

**Issue by chchang6** [1QB-Information-Technologies/openqemist#61]
Hi, I created an Anaconda environment with

```
conda create -n qistwg python=3
conda install numpy
pip install openqemist
```

The installation completed, but when trying to run a spin-unrestricted DFT calculation, I get

```
...
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
^CTraceback (most recent call last):
  File "TsPS-thieno.py", line 133, in <module>
    UKS_object.kernel()
  File "/home/cchang/.conda-envs/qistwg/lib/python3.7/site-packages/pyscf/lib/misc.py", line 578, in aliased_fn
    return fn(*args, **kwargs)
  File "/home/cchang/.conda-envs/qistwg/lib/python3.7/site-packages/pyscf/scf/hf.py", line 1476, in scf
    conv_check=self.conv_check, **kwargs)
  File "/home/cchang/.conda-envs/qistwg/lib/python3.7/site-packages/pyscf/scf/hf.py", line 143, in kernel
    vhf = mf.get_veff(mol, dm)
  File "/home/cchang/.conda-envs/qistwg/lib/python3.7/site-packages/pyscf/dft/uks.py", line 62, in get_veff
    n, exc, vxc = ni.nr_uks(mol, ks.grids, ks.xc, dm, max_memory=max_memory)
  File "/home/cchang/.conda-envs/qistwg/lib/python3.7/site-packages/pyscf/dft/numint.py", line 968, in nr_uks
    rho_b = make_rhob(idm, ao, mask, xctype)
  File "/home/cchang/.conda-envs/qistwg/lib/python3.7/site-packages/pyscf/dft/numint.py", line 1934, in make_rho
    return self.eval_rho(mol, ao, dms[idm], non0tab, xctype, hermi=1)
  File "/home/cchang/.conda-envs/qistwg/lib/python3.7/site-packages/pyscf/dft/numint.py", line 1883, in eval_rho
    return eval_rho(mol, ao, dm, non0tab, xctype, hermi, verbose)
  File "/home/cchang/.conda-envs/qistwg/lib/python3.7/site-packages/pyscf/dft/numint.py", line 177, in eval_rho
    rho[i] = _contract_rho(c0, ao[i])
  File "/home/cchang/.conda-envs/qistwg/lib/python3.7/site-packages/pyscf/dft/numint.py", line 651, in _contract_rho
    ctypes.c_int(nao), ctypes.c_int(ngrids))
KeyboardInterrupt

```
Environment looks like
```
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - blas=2.14=openblas
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py37h89c1867_1
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.5.0=h14aa051_18
  - libgfortran4=7.5.0=h14aa051_18
  - libgomp=9.3.0=h2828fa1_18
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libstdcxx-ng=9.3.0=h6de172a_18
  - ncurses=6.2=h58526e2_4
  - numpy=1.17.0=py37h99e49ec_0
  - numpy-base=1.17.0=py37h2f8d375_0
  - openssl=1.1.1j=h7f98852_0
  - pip=21.0.1=pyhd8ed1ab_0
  - python=3.7.10=hffdb5ce_100_cpython
  - python_abi=3.7=1_cp37m
  - readline=8.0=he28a2e2_2
  - setuptools=49.6.0=py37h89c1867_3
  - sqlite=3.35.2=h74cdb3f_0
  - tk=8.6.10=h21135ba_1
  - tzdata=2021a=he74cb21_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - pip:
    - attrs==20.3.0
    - cached-property==1.5.2
    - cffi==1.14.5
    - chardet==4.0.0
    - cryptography==3.4.6
    - cvxopt==1.2.6
    - cycler==0.10.0
    - decorator==4.4.2
    - dlx==1.0.4
    - docplex==2.20.204
    - fastdtw==0.3.4
    - forestopenfermion==0.0.6
    - funcsigs==1.0.2
    - h5py==3.2.1
    - idna==2.10
    - immutables==0.6
    - importlib-metadata==3.7.3
    - inflection==0.5.1
    - ipython-genutils==0.2.0
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - kiwisolver==1.3.1
    - lark==0.11.1
    - marshmallow==3.10.0
    - marshmallow-polyfield==5.10
    - matplotlib==3.3.4
    - mock==4.0.3
    - more-itertools==8.7.0
    - mpmath==1.2.1
    - msgpack==0.6.2
    - nest-asyncio==1.0.0
    - networkx==2.5
    - ntlm-auth==1.5.0
    - openfermion==0.11.0
    - openqemist==0.2.1
    - pandas==1.2.3
    - pillow==8.1.2
    - ply==3.11
    - psutil==5.8.0
    - pubchempy==1.0.4
    - pycparser==2.20
    - pyparsing==2.4.7
    - pyquil==2.28.0
    - pyrsistent==0.17.3
    - pyscf==1.6
    - python-dateutil==2.8.1
    - python-rapidjson==1.0
    - pytz==2021.1
    - pyzmq==19.0.2
    - qiskit==0.13.0
    - qiskit-aer==0.3.2
    - qiskit-aqua==0.6.1
    - qiskit-ibmq-provider==0.3.3
    - qiskit-ignis==0.2.0
    - qiskit-terra==0.10.0
    - qsharp==0.15.2102.129448
    - qsharp-chemistry==0.15.2102.129448
    - qsharp-core==0.15.2102.129448
    - quandl==3.6.1
    - quantum-grove==1.7.0
    - requests==2.25.1
    - requests-ntlm==1.1.0
    - rpcq==3.7.0
    - ruamel-yaml==0.16.13
    - ruamel-yaml-clib==0.2.2
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - six==1.15.0
    - sympy==1.7.1
    - threadpoolctl==2.1.0
    - tornado==6.1
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - websockets==7.0
    - zipp==3.4.1
```
Short of someone rebuilding a package, does anyone know the OpenBLAS environment variable that controls whether to print this or not? Thanks

**Comment by chchang6** [comment]
OK, solved my own problem. See https://www.rc.ucl.ac.uk/docs/Wiki_Export/software/done/OpenBLAS/
`export OPENBLAS_NUM_THREADS=1` stopped it, and kept the underlying OpenMP threading intact.

**Comment by RudiP4t1qbit** [comment]
Hi @chchang6. Thanks for using OpenQEMIST!

I don't know what the consequences for performance are of setting the `OPENBLAS_NUM_THREADS` environment variable. I'd recommend doing a bit of profiling to make sure that this isn't a causing performance problems.

This problem comes from the version of OpenBLAS that comes bundled with PySCF. We couldn't find a way to link PySCF to a different version of OpenBLAS in a pip installation. The two options for fixing this are:

1. Building PySCF from source, which allows you to link any BLAS implementation.
2. On a Linux OS, setting the `LD_PRELOAD` environment variable to force the operating system to load another implementation of BLAS. This is what we use in the OpenQEMIST Docker image.
https://github.com/1QB-Information-Technologies/openqemist/blob/master/docker_images/qemist/Dockerfile#L26

I hope this helps!
cc: @ValentinS4t1qbit, @TakeshiY4t1qbit

**Comment by chchang6** [comment]
Hi @RudiP4t1qbit, thanks for the info and sorry for the delay, I am just able to touch on this project again now.

I'm seeing OMP_NUM_THREADS Python processes with identical PIDs and PPIDs (distinct LWPs) running at 100% via ps, and the output is clean (i.e., not getting 36 copies of everything), so I think it's running as expected. Profiling is still a good idea, thanks.

When I'm using Anaconda and trying to read in a checkpoint file, it's failing with
  File "/home/cchang/.conda-envs/qistwg/lib/python3.7/site-packages/pyscf/lib/chkfile.py", line 159, in load_mol
    mol = gto.loads(fh5['mol'].value)
AttributeError: 'Dataset' object has no attribute 'value'

I'm trying to stay as close to instructions as possible, so could this be an h5py version incompatibility with PySCF 1.6? I didn't see a version restriction in the Dockerfile (which is very helpful, thank you for the link).

**Comment by chchang6** [comment]
This explains it https://github.com/lorenzwalthert/mlflow/commit/197a561d4b886eefb0963d5dcfa38a630b3657a4
May need to restrict h5py to < 3.0.0.
